### PR TITLE
user story 2 from esraa

### PR DESCRIPTION
**Pull request by esraafarh2017**
user story 2

### CODE REVIEW

**Comment by esraafarh2017** [comment]
ready for review

**Review by aysuahmadli — APPROVED** [review]
Looks great Esra, good job!!

**Review by Tinbite1 — APPROVED** [review]
Good Job Esra!

**Comment by esraafarh2017** [comment]
ready for merge

**Review by rmautia — APPROVED** [review]
Nice work

**Review by inesa7 — APPROVED** [review]
Nice work Esra!

**Pull request closed without merging**
